GET https://api.openf1.org/v1/sessions?year=2023
Accept: application/json
###
GET https://api.openf1.org/v1/meetings?year=2023
Accept: application/json

###
GET https://api.openf1.org/v1/drivers
Accept:  application/json

###
GET https://api.openf1.org/v1/car_data?driver_number=REPLACE&session_key=REPLACE
Accept:  application/json
###
GET https://api.openf1.org/v1/intervals?session_key=REPLACE&driver_number=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/laps?session_key=REPLACE&driver_number=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/location?session_key=REPLACE&driver_number=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/pit?session_key=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/position?session_key=REPLACE&driver_number=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/race_control?session_key=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/stints?session_key=REPLACE&driver_number=REPLACE
Accept: application/json
###
GET https://api.openf1.org/v1/weather?session_key=REPLACE
Accept: application/json
